#!/bin/zsh

__import "core/core"
__import "job/spinner"
__import "print/print"

local    line is_verbose=false
local -A zspec
local -a fail args

while (( $# > 0 ))
do
    case "$1" in
        --verbose)
            is_verbose=true
            ;;
        -*|--*)
            __die "$1: Unknown option\n"
            return 1
            ;;
        *)
            args+=("$1")
            ;;
    esac
    shift
done

for line in ${(u)${args[@]:gs:@::}}
do
    zspec=( ${(@f)"$(__parser__ "$line")"} )
    [[ $zspec[from] == "local" ]] && continue
    if [[ $zspec[from] != "oh-my-zsh" && ! -e $zspec[dir] ]] || [[ $zspec[from] == "oh-my-zsh" && ! -d ${zspec[dir]:h} ]]; then
        fail+=("$zspec[name]")
    fi
done

if (( $#fail > 0 )); then
    if $is_verbose; then
        __put "- \033[31m%s\033[m: not installed\n" "${(@nO)fail}"
    fi
    return 1
else
    return 0
fi
