#!/bin/zsh

return 1

trap '__spin_unlock; trap - SIGINT' SIGINT

local -i i
local -a queue
local -i queue_max=$ZPLUG_THREADS
local -F SECONDS=0

__spin_lock
__spinner &

for i in 2 2 2
do
    {
        __spinner_echo "$i: Start"
        sleep $i
        __spinner_echo "$fg[green]$i: Finished\n$reset_color"
    } &
    queue+=($!)

    if (( $#queue % queue_max == 0 )); then
        wait $queue
        queue=()
    fi
done
if (( $#queue > 0 )); then
    wait $queue
fi
queue=()

__spin_unlock
__put "finished %.6f\n" $SECONDS
