#!/bin/zsh

__die "\n"
return 1

trap '__spin_unlock; trap - SIGINT' SIGINT

local -i i
local -a queue
local -i queue_max=$ZPLUG_THREADS
local -F SECONDS=0

__spin_lock
__spinner &

for i in 2 2 2
do
    {
        __spinner_echo "$i: Start"
        sleep $i
        __spinner_echo "\033[32m$i: Finished\033[m"
    } &
    queue+=($!)

    if (( $#queue % queue_max == 0 )); then
        wait $queue
        queue=()
    fi
done
wait $queue
queue=()

__spin_unlock
__put "finished %.6f\n" $SECONDS
